# Generated by Django 4.1 on 2022-10-27 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_name', models.CharField(max_length=32, verbose_name='部门名称')),
            ],
        ),
        migrations.CreateModel(
            name='TesterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tester_name', models.CharField(max_length=64, verbose_name='测试人姓名')),
                ('password', models.CharField(max_length=64, verbose_name='员工密码')),
                ('depart_name', models.ForeignKey(default='互动直播测试小组', on_delete=django.db.models.deletion.CASCADE, to='AccountManage.department', verbose_name='部门')),
            ],
        ),
    ]
