# Generated by Django 4.1 on 2022-10-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testerinfo',
            name='password',
            field=models.CharField(max_length=64, verbose_name='密码'),
        ),
    ]
