# Generated by Django 4.1 on 2022-10-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManage', '0002_alter_testerinfo_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='管理员账号')),
                ('password', models.CharField(max_length=32, verbose_name='管理员密码')),
            ],
        ),
    ]
