# Generated by Django 4.1 on 2022-11-03 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManage', '0005_alter_account_account_belong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccountManage.testerinfo', verbose_name='测试账号归属'),
        ),
    ]
