# Generated by Django 4.1.2 on 2022-11-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManage', '0006_alter_account_account_belong'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_remarks',
            field=models.CharField(default='test', max_length=128, verbose_name='备注'),
        ),
    ]
