# Generated by Django 4.1.2 on 2022-11-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManage', '0007_account_account_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_remarks',
            field=models.CharField(max_length=128, verbose_name='备注'),
        ),
    ]
