# Generated by Django 4.1.5 on 2023-01-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManage', '0009_alter_account_account_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='HDID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=128, verbose_name='测试机')),
                ('zhuiwan', models.CharField(max_length=128, verbose_name='追玩')),
                ('Yomi', models.CharField(max_length=128, verbose_name='Yo语音')),
                ('YaYa', models.CharField(max_length=128, verbose_name='YaYa')),
                ('hdid_remarks', models.CharField(max_length=128, verbose_name='备注')),
            ],
        ),
    ]
