# Generated by Django 4.1.5 on 2023-01-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManage', '0010_hdid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdid',
            name='YaYa',
            field=models.CharField(max_length=128, null=True, verbose_name='YaYa'),
        ),
        migrations.AlterField(
            model_name='hdid',
            name='Yomi',
            field=models.CharField(max_length=128, null=True, verbose_name='Yo语音'),
        ),
        migrations.AlterField(
            model_name='hdid',
            name='hdid_remarks',
            field=models.CharField(max_length=128, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='hdid',
            name='zhuiwan',
            field=models.CharField(max_length=128, null=True, verbose_name='追玩'),
        ),
    ]
