# Generated by Django 4.1.5 on 2023-01-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManage', '0011_alter_hdid_yaya_alter_hdid_yomi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hdid',
            name='hdid_remarks',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_YY',
            field=models.CharField(max_length=128, null=True, verbose_name='测试账号YY'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_card',
            field=models.CharField(max_length=128, null=True, verbose_name='测试账号通行证'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_pwd',
            field=models.CharField(max_length=64, null=True, verbose_name='测试账号密码'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_uid',
            field=models.CharField(max_length=128, null=True, verbose_name='测试账号UID'),
        ),
    ]
