# Generated by Django 4.1.5 on 2023-02-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManage', '0012_remove_hdid_hdid_remarks_alter_account_account_yy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdid',
            name='remark',
            field=models.CharField(max_length=128, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='hdid',
            name='YaYa',
            field=models.CharField(max_length=64, null=True, verbose_name='YaYa'),
        ),
        migrations.AlterField(
            model_name='hdid',
            name='Yomi',
            field=models.CharField(max_length=64, null=True, verbose_name='Yo语音'),
        ),
        migrations.AlterField(
            model_name='hdid',
            name='phone',
            field=models.CharField(max_length=64, verbose_name='测试机'),
        ),
        migrations.AlterField(
            model_name='hdid',
            name='zhuiwan',
            field=models.CharField(max_length=64, null=True, verbose_name='追玩'),
        ),
    ]
