# Generated by Django 4.1.5 on 2023-02-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManage', '0013_hdid_remark_alter_hdid_yaya_alter_hdid_yomi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdid',
            name='remark',
            field=models.CharField(default='', max_length=128, null=True, verbose_name='备注'),
        ),
    ]
