# Generated by Django 4.1.2 on 2023-04-25 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManage', '0014_alter_hdid_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='testerinfo',
            name='operator_num',
            field=models.CharField(default=0, max_length=64, verbose_name='操作次数'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='account_belong',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='AccountManage.testerinfo', verbose_name='测试账号归属'),
        ),
    ]
