# Generated by Django 4.1.2 on 2023-04-25 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManage', '0015_testerinfo_operator_num_alter_account_account_belong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testerinfo',
            name='operator_num',
        ),
    ]
